name: Build Debug APKs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0

    - name: Check for UPDATE commit
      id: check_commit
      if: github.event_name == 'push'
      run: |
        echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
        echo "COMMIT_AUTHOR=$(git log -1 --pretty=%an)" >> $GITHUB_ENV

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
      if: github.event_name == 'workflow_dispatch' || (github.actor == 'DZZN-DEV' && contains(env.COMMIT_MESSAGE, 'UPDATE'))

    - name: Create Properties File
      run: touch local.properties
      if: github.event_name == 'workflow_dispatch' || (github.actor == 'DZZN-DEV' && contains(env.COMMIT_MESSAGE, 'UPDATE'))

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      if: github.event_name == 'workflow_dispatch' || (github.actor == 'DZZN-DEV' && contains(env.COMMIT_MESSAGE, 'UPDATE'))

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
      if: github.event_name == 'workflow_dispatch' || (github.actor == 'DZZN-DEV' && contains(env.COMMIT_MESSAGE, 'UPDATE'))

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: apk-debug versions
        path: app/build/outputs/apk/debug/*.apk
      if: github.event_name == 'workflow_dispatch' || (github.actor == 'DZZN-DEV' && contains(env.COMMIT_MESSAGE, 'UPDATE'))
